version: '3'

services:
  app:
    image: techno-flow-backend
    container_name: techno-flow-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: ./main
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: techno-flow-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=techno-flow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
