server:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  username: 'postgres'
  password: 'root'
  host: 'postgres'
#  host: 'localhost'
  port: '5432'
  dbname: 'techno-flow'
  sslmode: 'disable'

jwt:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days
